apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 2
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: mysql:5.6
          ports:
            - name: tpc
              protocol: TCP
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
               secretKeyRef: 
                key: MYSQL_ROOT_PASSWORD
                name: sql
            - name: MYSQL_PASSWORD
              valueFrom:
               secretKeyRef:
                key: MYSQL_PASSWORD
                name: sql
            - name: MYSQL_USER
              valueFrom:
               secretKeyRef:
                key: MYSQL_USER
                name: sql
             - name: MYSQL_DATABASE
               value: spring
